In [2]:
import torch

In [3]:
def function01(tensor: torch.Tensor, count_over: str) -> torch.Tensor:
    if count_over == 'columns':
        return tensor.mean(dim=0)
    elif count_over == 'rows':
        return tensor.mean(dim=1)

In [13]:
some_data = [[1, 2], [3, 4], [5, 6]]
some_tensor = torch.tensor(some_data, dtype=torch.float32)
some_tensor

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [14]:
function01(some_tensor, 'columns')

tensor([3., 4.])

In [15]:
function01(some_tensor, 'rows')

tensor([1.5000, 3.5000, 5.5000])

In [19]:
some_tensor.shape[1]

2

In [24]:
def function02(tensor: torch.Tensor) -> torch.Tensor:
    shape = tensor.shape[1]
    return torch.rand(shape, dtype=torch.float32, requires_grad=True)

In [25]:
function02(some_tensor)

tensor([0.3706, 0.5586], requires_grad=True)

In [31]:
n_features = 2         # Размерность указана для примера, не нужно использовать её в коде
n_objects = 300

w_true = torch.randn(n_features)
w_true

tensor([1.4068, 0.3196])

In [32]:
X = (torch.rand(n_objects, n_features) - 0.5) * 5

In [33]:
Y = X @ w_true + torch.randn(n_objects) / 2

In [39]:
def function03(x: torch.Tensor, y: torch.Tensor):
    shape = x.shape[1]
    w = torch.rand(shape, dtype=torch.float32, requires_grad=True)
    
    n_steps = 200
    step_size = 1e-2
    
    for i in range(n_steps):
        y_pred = torch.matmul(x, w)
        mse = torch.mean((y_pred - y) ** 2)
        
        if i < 20 or i % 10 == 0:
            print(f'MSE на шаге {i + 1} {mse.item():.5f}')
            
        mse.backward()
        
        with torch.no_grad():
            w -= w.grad * step_size
            
        w.grad.zero_()
    
    return w

In [40]:
function03(X, Y)

MSE на шаге 1 2.57571
MSE на шаге 2 2.39131
MSE на шаге 3 2.22156
MSE на шаге 4 2.06530
MSE на шаге 5 1.92145
MSE на шаге 6 1.78903
MSE на шаге 7 1.66712
MSE на шаге 8 1.55490
MSE на шаге 9 1.45158
MSE на шаге 10 1.35647
MSE на шаге 11 1.26890
MSE на шаге 12 1.18828
MSE на шаге 13 1.11406
MSE на шаге 14 1.04573
MSE на шаге 15 0.98282
MSE на шаге 16 0.92490
MSE на шаге 17 0.87157
MSE на шаге 18 0.82247
MSE на шаге 19 0.77727
MSE на шаге 20 0.73564
MSE на шаге 21 0.69732
MSE на шаге 31 0.44702
MSE на шаге 41 0.33729
MSE на шаге 51 0.28913
MSE на шаге 61 0.26797
MSE на шаге 71 0.25866
MSE на шаге 81 0.25456
MSE на шаге 91 0.25276
MSE на шаге 101 0.25196
MSE на шаге 111 0.25161
MSE на шаге 121 0.25146
MSE на шаге 131 0.25139
MSE на шаге 141 0.25136
MSE на шаге 151 0.25134
MSE на шаге 161 0.25134
MSE на шаге 171 0.25134
MSE на шаге 181 0.25133
MSE на шаге 191 0.25133


tensor([1.4190, 0.3203], requires_grad=True)

In [44]:
from torch import nn

In [54]:
def function04(x: torch.Tensor, y: torch.Tensor):
    n_features = x.shape[1]
    layer = nn.Linear(in_features=n_features, out_features=1)
    
    n_steps = 200
    step_size = 1e-2
    
    for i in range(n_steps):
        y_pred = layer(x).ravel()
    
        mse = torch.mean((y_pred - y) ** 2)
        
        if i < 20 or i % 10 == 0:
            print(f'MSE на шаге {i + 1} {mse.item():.5f}')
    
        mse.backward()
    
        with torch.no_grad():
            layer.weight -= layer.weight.grad * step_size
        
        layer.zero_grad()
        
    return layer

In [55]:
function04(X, Y)

MSE на шаге 1 2.22646
MSE на шаге 2 2.07369
MSE на шаге 3 1.93287
MSE на шаге 4 1.80306
MSE на шаге 5 1.68340
MSE на шаге 6 1.57310
MSE на шаге 7 1.47141
MSE на шаге 8 1.37768
MSE на шаге 9 1.29127
MSE на шаге 10 1.21161
MSE на шаге 11 1.13818
MSE на шаге 12 1.07049
MSE на шаге 13 1.00809
MSE на шаге 14 0.95056
MSE на шаге 15 0.89753
MSE на шаге 16 0.84864
MSE на шаге 17 0.80357
MSE на шаге 18 0.76202
MSE на шаге 19 0.72372
MSE на шаге 20 0.68841
MSE на шаге 21 0.65585
MSE на шаге 31 0.44198
MSE на шаге 41 0.34709
MSE на шаге 51 0.30498
MSE на шаге 61 0.28628
MSE на шаге 71 0.27797
MSE на шаге 81 0.27428
MSE на шаге 91 0.27264
MSE на шаге 101 0.27191
MSE на шаге 111 0.27159
MSE на шаге 121 0.27145
MSE на шаге 131 0.27138
MSE на шаге 141 0.27135
MSE на шаге 151 0.27134
MSE на шаге 161 0.27133
MSE на шаге 171 0.27133
MSE на шаге 181 0.27133
MSE на шаге 191 0.27133


Linear(in_features=2, out_features=1, bias=True)